---
swagger: "2.0"
info:
  description: "Nothing"
  version: "1.0"
  title: "PACT Provider"
schemes:
  - "http"
paths:
  /test:
    get:
      operationId: "getTest"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
